export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST '
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const GET_PROFILES = 'GET_PROFILES'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const PROFILE_RESET = 'PROFILE_RESET';
export const GET_REPOS = 'GET_REPOS';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';


